/* Список графики, которая есть в папке art/ (создаётся tools/build-art.py). */
const ART_FILES = {
 "gems/board": "art/gems/board.webp",
 "gems/emerald": "art/gems/emerald.webp",
 "gems/onyx": "art/gems/onyx.webp",
 "gems/ruby": "art/gems/ruby.webp",
 "gems/sapphire": "art/gems/sapphire.webp",
 "heroes/dwarf-m-body-1": "art/heroes/dwarf-m-body-1.webp",
 "heroes/dwarf-m-body-2": "art/heroes/dwarf-m-body-2.webp",
 "heroes/dwarf-m-body-3": "art/heroes/dwarf-m-body-3.webp",
 "heroes/dwarf-m-portrait": "art/heroes/dwarf-m-portrait.webp",
 "heroes/elf-f-body-1": "art/heroes/elf-f-body-1.webp",
 "heroes/elf-f-body-2": "art/heroes/elf-f-body-2.webp",
 "heroes/elf-f-body-3": "art/heroes/elf-f-body-3.webp",
 "heroes/elf-f-portrait": "art/heroes/elf-f-portrait.webp",
 "heroes/human-m-body-1": "art/heroes/human-m-body-1.webp",
 "heroes/human-m-body-2": "art/heroes/human-m-body-2.webp",
 "heroes/human-m-body-3": "art/heroes/human-m-body-3.webp",
 "heroes/human-m-portrait": "art/heroes/human-m-portrait.webp",
 "heroes/lizard-m-body-1": "art/heroes/lizard-m-body-1.webp",
 "heroes/lizard-m-body-2": "art/heroes/lizard-m-body-2.webp",
 "heroes/lizard-m-body-3": "art/heroes/lizard-m-body-3.webp",
 "heroes/lizard-m-portrait": "art/heroes/lizard-m-portrait.webp",
 "items/hammer": "art/items/hammer.webp",
 "items/potion": "art/items/potion.webp",
 "monsters/bandit": "art/monsters/bandit.webp",
 "monsters/dragon": "art/monsters/dragon.webp",
 "monsters/dragon-body": "art/monsters/dragon-body.webp",
 "monsters/ghoul": "art/monsters/ghoul.webp",
 "monsters/goblin": "art/monsters/goblin.webp",
 "monsters/orc": "art/monsters/orc.webp",
 "monsters/orcShaman": "art/monsters/orcShaman.webp",
 "monsters/rat": "art/monsters/rat.webp",
 "monsters/skeleton": "art/monsters/skeleton.webp",
 "monsters/wolf": "art/monsters/wolf.webp",
 "monsters/wraith": "art/monsters/wraith.webp",
 "ui/emblem-dwarf": "art/ui/emblem-dwarf.webp"
};
